### ISSUE TITLE
[bug] ticking entity crash when harvesting complex crops cucumber with pnc-repressurized drone

### ISSUE THREAD

**Issue by wideblaze** [Icedice9/Complex-Crops#3]
Minecraft 1.12.2

Forge 14.23.5.2823

Modpack Digsite 1.0.01

Complex Crops 1.12.2-4.1.3
pneumaticcraft-repressurized-1.12.2-0.11.3-366

ticking entity crash when harvesting mature complex crops cucumber with pnc-repressurized drone 

the exact complex crops code issue and crash log in referenced issue link:

wideblaze/DigSite#6

**Comment by mattcloward** [comment]
So sorry for not getting back to you sooner on this! I've been busy with (insert [in]valid excuse about college workload). I am working on an update to fix the bug and I'm hoping to have it out by the end of this week or next. Thanks for your patience and for putting my mod in your pack!

**Comment by wideblaze** [comment]
no worries -- I kinda knew that going in -- but it tested well, I wanted something different,  and it fit in with the story (liked the idea of cucumbers being used in cloning process -- sorta like the invasion of the body snatchers movie)  

I removed drone recipe in the meantime (as not needed anyway) so no more crashes

Hey, while you are under the hood, could you make a config option to disable complex crops seeds from breaking grass?

**Comment by mattcloward** [comment]
Haha! Yeah, the pickles turned out pretty fun.
For the config, you are asking for the ability to turn off seeds dropping from tall grass right? Would you like a config feature that has them appear in loot chests or as a rare drop from zombies etc like the other seeds, or do you have something else in mind?

**Comment by wideblaze** [comment]
feel free to add that as another option -- but I'm just looking to turn the tall grass off.

I created a custom seed recipes/quests for the pack but later realized no one was ever going to use it because you can simply get them from breaking grass. Example seeds+waterbucket = rice seeds.

**Comment by mattcloward** [comment]
Haha! Sounds like a problem. 😄 Yeah, I’ll add the config feature for the next update. Thanks for your help!

**Comment by mattcloward** [comment]
I just put out a release today that  should fix the issue you were seeing. I also added config to disable the different ways of obtaining the seeds. Let me know if everything works!

**Comment by wideblaze** [comment]
testing

**Comment by wideblaze** [comment]
looks good -- will put in next release
thanks!

**Comment by mattcloward** [comment]
Hurray! Corn harvesting is still a bit buggy, so I’ll be putting out a smaller release to fix some of those issues. Let me know if you see anything else.

**Comment by wideblaze** [comment]
ummm -- when I go back into the world where I was testing drone harvesting of corn:
Exception ticking world

https://paste.dimdev.org/iqixukikes.mccrash

**Comment by mattcloward** [comment]
That's odd. I don't have any hash maps in my code, so I'm not entirely sure what's going on here. I'll download your modpack later today and see if I can figure out what's going on.

**Comment by wideblaze** [comment]
Steps to reproduce:

go into creative
plant a corn field
bone meal to maturity
place a harvesting drone
have it harvest corn (leave it on ground)
close to title screen
go back into game
crash

**Comment by mattcloward** [comment]
I was able to reproduce the bug, but haven't found out yet what is causing it. ConcurrentModificationExceptions are time sensitive, so it's difficult to reproduce the crash consistently. I'll try to look at it again today to see what I can find. Thank you for your patience!

**Comment by wideblaze** [comment]
ok great

**Comment by mattcloward** [comment]
Status update: I was able to make it so the drones replant the bottom block instead of just the top one. The crash still happens occasionally, but I still haven't been able to figure out why. It may be a pnc bug because its referring to "EntityTracker.sendLeashedEntitiesInChunk" and the corn doesn't do anything with the entity tracker. The crash doesn't seem to happen with vanilla crops though. Perhaps the pnc author has an idea?
